### ISSUE TITLE
Use GitHub labels instead of prefixes on your issues

### ISSUE THREAD

**Issue by baynezy** [Jaffacakes82/MentorMe#9]
Instead of using prefixes like Improvement: and Technical Debt: on your issue titles. Use GitHub labels. They look great in Waffle.io as well

https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/

**Comment by baynezy** [comment]
Some examples of the ones I use are here:-

https://github.com/baynezy/Html2Markdown/labels

**Comment by Jaffacakes82** [comment]
Implemented.

**Comment by baynezy** [comment]
@Jaffacakes82 - I think you may have inadvertently broken your Waffle.io set up doing this.

![image](https://cloud.githubusercontent.com/assets/1049999/25328812/33cfe70a-28d1-11e7-8bb1-518327c787a9.png)

Go into your Waffle.io settings and re-bind the Ready column to the Ready label

**Comment by Jaffacakes82** [comment]
Cheers :).
